- .angular-cli.json
- src/app/app.component.html
- src/app/packages/menu-items/algorithms/algorithms/algorithms.component.ts
- src/app/packages/menu-items/cases/cases/cases.component.html
- src/app/packages/menu-items/cases/cases/cases.component.ts
- src/app/packages/menu-items/data-layers/data-layers/data-layers.component.ts
- src/app/packages/menu-items/filters/filters/filters.component.ts
- src/app/packages/menu-items/settings/settings/settings.component.ts
- src/app/packages/menu-items/tools/tools/tools.component.ts
- src/app/packages/menu/menu/menu.component.ts
- src/app/packages/utils/infinite-scroll/infinite-scroll.directive.ts
> change prefix

- package.json
> upgrade event drops commit

- package.json
> ansyn-24 add ngrx to master

- src/app/app.module.ts
- src/app/packages/imagery/api/imageryCommunicator.ts
- src/app/packages/imagery/manager/imageryManager.ts
- src/app/packages/imagery/model/model.ts
- src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.html
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
- src/app/packages/menu-items/imagerySandBox/imagery-sand-box.module.ts
- src/app/packages/menu-items/imagerySandBox/index.ts
- src/app/packages/menu-items/imagerySandBox/package.json
- src/app/packages/menu-items/index.ts
> #90 imagerySandBox added

- package.json
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/packages/cesium-map/cesium-map.module.ts
- src/app/packages/cesium-map/index.ts
- src/app/packages/cesium-map/map/cesium-map.ts
- src/app/packages/cesium-map/map/cesium.component.ts
- src/app/packages/cesium-map/package.json
- src/app/packages/imagery/api/imageryCommunicator.ts
- src/app/packages/imagery/imageryComponent/imagery.component.ts
- src/app/packages/imagery/index.ts
- src/app/packages/imagery/manager/imageryManager.ts
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.html
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
#126 CesiumMap container package added
> #126 CesiumMap container package added

- package.json
> #137 Integration fix

- package.json
- src/app/app.module.ts
- src/app/packages/cesium-map/map/cesium.component.ts
- src/app/packages/imagery/api/imageryCommunicator.service.ts
- src/app/packages/imagery/api/imageryCommunicator.ts
- src/app/packages/imagery/imagery.module.ts
- src/app/packages/imagery/imageryComponent/imagery.component.spec.ts
- src/app/packages/imagery/imageryComponent/imagery.component.ts
- src/app/packages/imagery/manager/imageryManager.ts
- src/app/packages/imagery/model/model.ts
- src/app/packages/imageryOpenLayerMap/imageryOpenLayerMap.module.ts
- src/app/packages/imageryOpenLayerMap/index.ts
- src/app/packages/imageryOpenLayerMap/map/openLayer.component.ts
- src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts
- src/app/packages/imageryOpenLayerMap/package.json
- src/app/packages/imageryOpenLayerMap/sourceProviders/OpenLayerOSMSourceProvider.ts
- src/app/packages/imageryOpenLayerMap/sourceProviders/OpenLayerTileWMSSourceProvider.ts
- src/app/packages/map-source-provider/index.ts
- src/app/packages/map-source-provider/map-source-provider.module.ts
- src/app/packages/map-source-provider/models/models.ts
- src/app/packages/map-source-provider/services/map-source-provider-container.service.spec.ts
- src/app/packages/map-source-provider/services/map-source-provider-container.service.ts
- src/configuration/configuration.dev.ts
- src/configuration/configuration.int.ts
- src/configuration/configuration.prod.ts
- src/configuration/configuration.ts
> #138 Add Imagery Configuratiun that loads default geo sources

- src/app/app-reducers/effects/menu.app.effects.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/container/overlays-container.component.html
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/effects/overlays.effects.ts
- src/app/packages/overlays/index.ts
- src/app/packages/overlays/timeline/timeline.component.spec.ts
- src/app/packages/overlays/timeline/timeline.component.ts
> add to - from to timeline 

- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/packages/imagery/imagery/imagery.component.spec.ts
- src/app/packages/imagery/imagery/imagery.component.ts
- src/app/packages/imagery/manager/imageryManager.ts
- src/app/packages/imagery/model/model.ts
- src/app/packages/imageryOpenLayerMap/map/openLayer.component.ts
- src/app/packages/imageryOpenLayerMap/map/openLayerMap.ts
- src/app/packages/imageryOpenLayerMap/sourceProviders/openLayersIDAHOSourceProvider.ts
- src/app/packages/imageryOpenLayerMap/sourceProviders/openLayersOSMSourceProvider.ts
- src/app/packages/imageryOpenLayerMap/sourceProviders/openLayersTileWMSSourceProvider.ts
- src/app/packages/map-source-provider/models/models.ts
- src/app/packages/map-source-provider/services/map-source-provider-container.service.spec.ts
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
- src/configuration/configuration.dev.ts
- src/configuration/configuration.int.ts
- src/configuration/configuration.prod.ts
- src/configuration/configuration.ts
> #138 #187 Integration fix

- src/app/app-reducers/effects/layers.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/packages/menu-items/layers-manager/effects/layers.effects.ts
- src/app/packages/menu-items/layers-manager/reducers/layers.reducer.ts
> finish with #199

- src/app/packages/menu-items/layers-manager/services/data-layers.service.spec.ts
- src/app/packages/menu-items/layers-manager/services/data-layers.service.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/configuration/configuration.dev.ts
overlays service is sending bounding box of the polygon now
config updated to the new layers api
> data-layers.service now obeys the new mock api.

- dockerfile
added dockerfile to create docker from dist directory
> added dockerfile for client app

- src/app/packages/map-facade/components/imagery-status/imagery-status.component.html
- src/app/packages/map-facade/components/imagery-status/imagery-status.component.less
- src/app/packages/status-bar/status-bar/status-bar.component.html
- src/app/packages/status-bar/status-bar/status-bar.component.less
- src/styles.less
> Back to world view button - status-bar (UI)

- src/app/ansyn/ansyn.component.html
- src/app/ansyn/ansyn.component.ts
- src/app/app-models/map-source-providers/open-layers-BING-source-provider.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app.module.ts
- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/imagery/imagery-component/manager/imagery.component.manager.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.ts
- src/app/packages/map-facade/components/imagery-status/imagery-status.component.html
- src/app/packages/map-facade/components/imagery-status/imagery-status.component.spec.ts
- src/app/packages/map-facade/components/imagery-status/imagery-status.component.ts
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
- src/app/packages/open-layer-center-marker-plugin/plugin/center-marker-plugin.ts
- src/app/packages/status-bar/status-bar/status-bar.component.html
- src/app/packages/status-bar/status-bar/status-bar.component.ts
- src/configuration/configuration.dev.ts
- src/configuration/configuration.ts
Back to world logic added #242 
Fix Bug #291 
Bing map added
center map plugin default set to enabled = false
> fix #242 #291

- src/app/app-reducers/app-reducers.module.ts
- src/app/app-reducers/effects/cases.app.effects.spec.ts
- src/app/app-reducers/effects/cases.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/overlays.app.effects.spec.ts
- src/app/app-reducers/effects/overlays.app.effects.ts
- src/app/packages/menu-items/cases/services/cases.service.spec.ts
- src/app/packages/menu-items/cases/services/cases.service.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/container/overlays-container.component.html
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/effects/overlays.effects.spec.ts
- src/app/packages/overlays/effects/overlays.effects.ts
- src/app/packages/overlays/timeline/timeline.component.css
- src/app/packages/overlays/timeline/timeline.component.spec.ts
- src/app/packages/overlays/timeline/timeline.component.ts
resolve #173 
resolve #281 
resolve #244
> communicate between case and the timeline

- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.html
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
- src/app/packages/menu-items/imagerySandBox/imagery-sand-box.module.ts
- src/app/packages/overlays/index.ts
- src/app/packages/overlays/models/overlay.model.ts
- src/configuration/cases/default_case.ts
resolve #296 ,
this is working now only from the sanbox
> add ability to change time in the overlays loading

- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/status-bar/status-bar/status-bar.component.html
- src/app/packages/status-bar/status-bar/status-bar.component.less
- src/app/packages/status-bar/status-bar/status-bar.component.spec.ts
- src/app/packages/status-bar/status-bar/status-bar.component.ts
> Add navigation by keyboard keys

- src/app/app-models/map-source-providers/open-layers-BING-source-provider.ts
- src/app/app-reducers/effects/filters.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app.module.ts
- src/app/packages/imagery/imagery-component/imagery.component.spec.ts
- src/app/packages/imagery/imagery-component/imagery.component.ts
- src/app/packages/imagery/imagery-component/manager/imagery.component.manager.ts
- src/app/packages/menu-items/filters/effects/filters.effects.ts
Removed type container and using angular container instead
> Remove type container

- src/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/app-reducers/effects/cases.app.effects.spec.ts
- src/app/app-reducers/effects/cases.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/overlays.app.effects.spec.ts
- src/app/app-reducers/effects/overlays.app.effects.ts
- src/app/app.module.ts
- src/app/packages/core/actions/empty.action.ts
- src/app/packages/core/models/overlay.model.ts
- src/app/packages/imagery/communicator-service/communicator.service.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/map-facade/reducers/map.reducer.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/effects/overlays.effects.spec.ts
- src/app/packages/overlays/effects/overlays.effects.ts
- src/app/packages/overlays/models/base-overlay-source-provider.model.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/app/packages/overlays/timeline/timeline.component.ts
#377 fix pin point loading exception
Fix loadin overlay from case that is not presented in timeline
> Fix bug377  pin point loading exception

- src/app/app-providers/overlay-source-providers/idaho-source-provider.ts
Fixed the color for 8 bands in idaho provider
> fixed color presenting for 8 bands

- src/app/app-reducers/effects/context/context-entity.app.effect.spec.ts
- src/app/app-reducers/effects/context/context-entity.app.effect.ts
- src/app/app-visualizers/context-entity.visualizer.ts
- src/app/packages/core/utils/time.ts
- src/app/packages/menu-items/cases/services/cases.service.ts
> fix #478, time label added

- package.json
- src/app/app-reducers/app-reducers.module.ts
- src/app/packages/core/models/index.ts
- src/app/packages/core/models/overlay.model.ts
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.html
- src/app/packages/menu-items/imagerySandBox/component/imagery-sand-box.component.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/models/overlay.model.ts
- src/app/packages/overlays/reducers/overlays.reducer.spec.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/app/packages/overlays/timeline/timeline.component.css
- src/app/packages/overlays/timeline/timeline.component.spec.ts
- src/app/packages/overlays/timeline/timeline.component.ts
- src/main.ts
> add event drops shapes and filters

- src/app/app-visualizers/context-entity.visualizer.ts
- src/app/packages/core/utils/time.ts
> update context entity color and time format

- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.spec.ts
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.html
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.less
- src/app/packages/open-layers-map/map/open-layers-map.ts
#416 
openlayers north arrow added
> add openlayers north arrow

- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/status-bar/status-bar/status-bar.component.less
> 306 fix timeline reset zoom

- src/app/packages/map-facade/components/context-menu/context-menu.component.less
- src/styles/styles.less
- src/styles/z-index-globals.less
> 2 css bugs

- src/app/app-reducers/app-reducers.module.ts
- src/app/packages/login/login/login.component.spec.ts
- src/app/packages/login/login/login.component.ts
resolve #607 change function from navigate to navigateByUrl
> bug after loading with link without login

- src/app/app-reducers/app-reducers.module.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/map/context-menu.app.effects.spec.ts
- src/app/packages/core/utils/geo.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.html
- src/app/packages/map-facade/components/context-menu/context-menu.component.less
- src/app/packages/map-facade/components/context-menu/context-menu.component.ts
- src/app/packages/map-facade/services/map-facade.service.ts
- src/app/packages/open-layers-map/map/map.component.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
> feat(pin-point): set pin point from context menu

- package.json
- scripts/fix-packages.js
- src/app/app-reducers/app-reducers.module.ts
No more doing that manually
@yairtawil
> script(fix-packages): add a precommit script for fixing packages import path

- src/app/connection-packages/cases-router/effects/cases-router.effects.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
… default case(with queryParams)
> Fix bug 'geo-point input does not affect the case'

- src/app/packages/menu-items/filters/components/enum-filter-container/enum-filter-container.component.less
> Fix Cosmetic bug- filters menu #568

- src/app/ansyn/ansyn.module.ts
- src/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/app-reducers/effects/cases.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/overlays.app.effects.spec.ts
- src/app/app-reducers/effects/status-bar.app.effects.spec.ts
- src/app/packages/menu-items/cases/components/cases-modal-container/cases-modal-container.component.spec.ts
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.spec.ts
- src/app/packages/menu-items/cases/components/cases-tools/cases-tools.component.spec.ts
- src/app/packages/menu-items/cases/components/delete-case/delete-case.component.spec.ts
- src/app/packages/menu-items/cases/components/edit-case/edit-case.component.spec.ts
- src/app/packages/menu-items/cases/components/save-case/save-case.component.spec.ts
- src/app/packages/menu-items/cases/effects/cases.effects.spec.ts
- src/app/packages/menu-items/cases/services/cases.service.spec.ts
- src/app/packages/menu-items/cases/services/cases.service.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.spec.ts
- src/app/packages/menu-items/filters/services/filters.services.spec.ts
- src/app/packages/menu-items/layers-manager/components/layer-tree/layer-tree.component.spec.ts
- src/app/packages/menu-items/layers-manager/components/layers-manager/layers-manager.component.spec.ts
- src/app/packages/menu-items/layers-manager/effects/layers.effects.spec.ts
- src/app/packages/menu-items/layers-manager/services/data-layers.service.spec.ts
- src/app/packages/menu-items/layers-manager/services/data-layers.service.ts
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/overlays.module.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
use HttpClient instead of Http for better performance and readability
> refactor(): use HttpClient instead of Http for better performance and readability

- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.html
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.less
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.ts
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.html
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.less
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.spec.ts
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.ts
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.html
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.less
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.spec.ts
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.ts
- src/app/packages/menu-items/tools/tools/tools.component.ts
> Improve go-to item look and feel 

- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
> fix(histogram): linter chagnes

- src/app/app-providers/map-source-providers/open-layers-MapBox-source-provider.ts
- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
> adding min zoom to openlayers map

- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/imagery/model/imap.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.ts
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/open-layers-map/map/open-layers-map.ts
> fix(pin point): css changes for cursor position, remove anchor option

- .angular-cli.json
- package.json
- src/app/packages/map-facade/effects/map.effects.ts
- src/app/packages/menu/menu/menu.component.less
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/overlays/timeline/timeline.component.ts
take event drops from npm instead of github
> change event-drops package source

- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/map/visualizers.app.effects.ts
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/menu-items/tools/actions/tools.actions.ts
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.spec.ts
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.ts
- src/app/packages/menu-items/tools/tools/tools.component.html
- src/app/packages/menu-items/tools/tools/tools.component.spec.ts
- src/app/packages/menu-items/tools/tools/tools.component.ts
- src/app/packages/open-layer-visualizers/index.ts
- src/app/packages/open-layer-visualizers/open-layer-visualizers.module.ts
- src/app/packages/open-layer-visualizers/tools/goto.visualizer.ts
- src/assets/icons/tools/goto-map-marker.svg
- added marker on the map for goto
- added two new actions for goto expand and for goto input changed
resolve #491
> Goto marker

- src/app/app-reducers/app-reducers.module.ts
- src/app/packages/overlays/reducers/overlays.reducer.spec.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
> add validation before insert time to the store

- confd/production.tmpl
- package.json
- src/app/app-reducers/effects/map/visualizers.app.effects.ts
- src/app/packages/type-container/services/type-container.service.spec.ts
- src/app/packages/type-container/type-container.module.spec.ts
- src/assets/config/app.config.json
- src/main.ts
> enableProdMode and change to bing  map source

- src/app/packages/core/components/overlay-text/overlay-text.component.html
- src/app/packages/map-facade/components/imagery-status/imagery-status.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
> Changed world view to base map text

- src/app/app-reducers/effects/cases.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/status-bar.app.effects.spec.ts
- src/app/packages/core/utils/toast/toast/toast.component.html
- src/app/packages/core/utils/toast/toast/toast.component.less
- src/app/packages/core/utils/toast/toast/toast.component.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/effects/overlays.effects.spec.ts
- src/app/packages/overlays/models/base-overlay-source-provider.model.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/status-bar/actions/status-bar.actions.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
- src/app/packages/status-bar/reducers/status-bar.reducer.ts
- src/assets/icons/status-bar/alert.svg
> Bug (customer site ): image source fails to open from timeline with no notification to the user #231

- src/app/app-reducers/effects/menu.app.effects.ts
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.html
- src/app/packages/menu-items/tools/tools/tools.component.less
- src/app/packages/menu/actions/menu.actions.ts
- src/app/packages/menu/helpers/index.ts
- src/app/packages/menu/helpers/menu-session.helper.ts
- src/app/packages/menu/index.ts
- src/app/packages/menu/menu/menu.component.less
- src/app/packages/menu/menu/menu.component.spec.ts
- src/app/packages/menu/menu/menu.component.ts
- src/app/packages/menu/models/index.ts
- src/app/packages/menu/models/menu-session-state.model.ts
- src/app/packages/menu/reducers/menu.reducer.ts
> fix(menu): Menu state should be saved ( sessionStorage )

- src/app/packages/status-bar/components/status-bar/status-bar.component.less
> fix(status-bar): the filters should be on the right side till the middle of the screen

- src/app/ansyn/ansyn/ansyn.component.ts
- src/app/packages/menu-items/tools/tools/tools.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.less
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
> status bar - click next does not reset the favorites star

- src/app/app-providers/map-source-providers/open-layers-BING-source-provider.ts
- src/app/app-providers/map-source-providers/open-layers-IDAHO-source-provider.ts
- src/app/app-providers/map-source-providers/open-layers-MapBox-source-provider.ts
- src/app/app-providers/map-source-providers/open-layers-OSM-source-provider.ts
- src/app/app-providers/map-source-providers/open-layers-TileWMS-source-provider.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/status-bar.app.effects.spec.ts
- src/app/packages/core/utils/toast/toast/toast.component.less
- src/app/packages/imagery/model/base-source-provider.model.ts
- src/app/packages/open-layers-map/map/map.component.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/overlays/container/overlays-container.component.less
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/effects/overlays.effects.spec.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
- src/app/packages/type-container/services/type-container.service.spec.ts
- src/app/packages/type-container/type-container.module.spec.ts
- src/main.ts
small change to constructor logic + lint
> refactor(maps): small change to constructor logic

- src/app/app-reducers/effects/filters.app.effects.ts
- src/app/packages/menu-items/filters/components/filter-container/filter-container.component.html
- src/app/packages/menu-items/filters/components/filter-container/filter-container.component.ts
- src/app/packages/menu-items/filters/effects/filters.effects.ts
- src/app/packages/menu-items/filters/models/metadata/filter-metadata.interface.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
resolve https://github.com/AnSyn/ansyn/issues/652
> fix(filters): deselect previously deselected items

- src/app/app-providers/overlay-source-providers/idaho-source-provider.ts
> fix(idaho): switch sensor name and type

- src/app/ansyn/ansyn.menu-items.ts
- src/app/app-reducers/effects/menu.app.effects.spec.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.html
- src/app/packages/map-facade/components/context-menu/context-menu.component.less
- src/app/packages/menu/menu/menu.component.html
- src/app/packages/menu/menu/menu.component.less
- src/app/packages/menu/models/menu-item.model.ts
- src/app/packages/menu/reducers/menu.reducer.spec.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
- src/app/packages/status-bar/components/timeline-timepicker/timeline-timepicker.component.html
- src/assets/app-loader/app-loader.js
> fix(icons): change some svgs to icons

- src/app/packages/map-facade/services/map-facade.service.ts
> fix(maps): active window always remains active and presented

- src/app/app-reducers/effects/menu.app.effects.ts
- src/app/packages/menu-items/filters/effects/filters.effects.ts
- src/app/packages/menu/actions/menu.actions.ts
- src/app/packages/menu/menu/menu.component.html
- src/app/packages/menu/menu/menu.component.spec.ts
- src/app/packages/menu/menu/menu.component.ts
> fix(menu, filters): 'show only favorites' indication in the filter menu badge

- src/app/app-providers/map-source-providers/open-layers-BING-source-provider.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
resolve https://github.com/AnSyn/ansyn/issues/713
> fix(zoom): move max zoom strictly to bing

- src/app/ansyn/ansyn/ansyn.component.less
- src/app/packages/core/less/z-index-globals.less
- src/app/packages/core/utils/toast/toast/toast.component.less
- src/app/packages/menu-items/cases/actions/cases.actions.ts
- src/app/packages/menu-items/cases/components/cases-modal-container/cases-modal-container.component.less
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.html
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.less
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.spec.ts
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.ts
- src/app/packages/menu-items/cases/components/edit-case/edit-case.component.less
- src/app/packages/menu-items/cases/effects/cases.effects.spec.ts
- src/app/packages/menu-items/cases/reducers/cases.reducer.spec.ts
- src/app/packages/menu-items/cases/reducers/cases.reducer.ts
> Pressing case edit button multiple times opens multiple dialogs

- src/app/packages/map-facade/components/context-menu/context-menu.component.html
- src/app/packages/map-facade/components/context-menu/context-menu.component.spec.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.ts
- src/styles/icons.less
> fix(context-menu): right click

- src/app/app-reducers/effects/filters.app.effects.ts
- src/app/app-reducers/effects/layers.app.effects.ts
- src/app/app-reducers/effects/menu.app.effects.ts
- src/app/app-reducers/effects/overlays.app.effects.ts
- src/app/connection-packages/cases-map/effects/cases-map.effects.ts
- src/app/connection-packages/cases-router/effects/cases-router.effects.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.ts
- src/app/packages/menu-items/filters/actions/filters.actions.ts
- src/app/packages/menu-items/filters/components/filters-collection/filters-collection.component.ts
- src/app/packages/menu-items/filters/effects/filters.effects.ts
- src/app/packages/menu-items/filters/services/filters.service.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
> fix(filters): Filters from case always displayed although there are no overlays

- confd/production.tmpl
> bug(config): default case has no filters

- src/app/app-reducers/effects/status-bar.app.effects.ts
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
- src/app/packages/status-bar/reducers/status-bar.reducer.ts
> fix(status-bar): overlays amount indication should not be affected by timeline zooming

- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.html
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.html
> fix(tools): Go to tool - input is affected by mouse scroll

- src/app/packages/menu-items/filters/models/metadata/enum-filter-metadata.ts
> fix(filters): when collapsing a category 'filtered indication' always appears

- src/app/packages/menu-items/tools/tools/tools.component.html
- src/app/packages/menu-items/tools/tools/tools.component.less
> fix(tools): add active status and change active style

- src/app/packages/open-layer-visualizers/overlays/polyline-visualizer.ts
> fix(polyline): add z-index to the active polyline

- src/app/app-reducers/app-reducers.module.ts
- src/app/app-reducers/effects/filters.app.effects.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map/context-menu.app.effects.ts
- src/app/app-reducers/effects/map/visualizers.app.effects.ts
- src/app/app-reducers/effects/overlays.app.effects.spec.ts
- src/app/app-reducers/effects/overlays.app.effects.ts
- src/app/connection-packages/cases-router/effects/cases-router.effects.ts
- src/app/packages/overlays/container/overlays-container.component.spec.ts
- src/app/packages/overlays/container/overlays-container.component.ts
- src/app/packages/overlays/effects/overlays.effects.ts
- src/app/packages/overlays/reducers/overlays.reducer.spec.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/app/packages/overlays/timeline/timeline.component.ts
> fix(overlays): another effect instead of manual dispatch

- src/app/packages/map-facade/components/context-menu/context-menu.component.spec.ts
- src/app/packages/map-facade/components/context-menu/context-menu.component.ts
> fix(context-menu): enabled buttons are falsely enabled

- src/app/app-reducers/effects/map.app.effects.ts
> fix742-bug(favorites): check showOnlyFavorites when an overly is being favorited as well

- confd/production.tmpl
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/packages/core/utils/calc-extent.spec.ts
- src/app/packages/core/utils/calc-extent.ts
- src/app/packages/core/utils/index.ts
- src/app/packages/map-facade/models/map-config.model.ts
- src/app/packages/map-facade/models/map-facade.config.ts
- src/assets/config/app.config.json
- src/main.ts
resolve #729 
@idanbarak 10% seems enough.
Do you want a demo, or just merge it and you'll see it next version?
> fix(map-overlay): extent not moving when intersects with the screen at least 10%

- package.json
- src/app/packages/status-bar/components/timeline-timepicker/timeline-timepicker.component.ts
> fix(flatpickr): upgrade version

- src/app/packages/core/utils/geo.ts
> merge for 528 fix

- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/packages/core/utils/geo.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
> fix(geo): use circle instead of point for query radius

- src/app/app-providers/app-providers.module.ts
- src/app/app-reducers/effects/map.app.effects.spec.ts
- src/app/app-reducers/effects/map.app.effects.ts
- src/app/app-reducers/effects/map/visualizers.app.effects.spec.ts
- src/app/app-reducers/effects/map/visualizers.app.effects.ts
- src/app/app-reducers/effects/status-bar.app.effects.spec.ts
- src/app/app-reducers/effects/status-bar.app.effects.ts
- src/app/packages/cesium-map/map/cesium-map.ts
- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/imagery/model/imap.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/open-layer-visualizers/icon.visualizer.ts
- src/app/packages/open-layers-map/disabled-map/open-layers-disabled-map.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/status-bar/actions/status-bar.actions.ts
- src/app/packages/status-bar/reducers/status-bar.reducer.spec.ts
- src/app/packages/status-bar/reducers/status-bar.reducer.ts
resolved #767
replace #792 , #800
> Refactor(767 pinpoint)externalize as visualizer3

- src/tsconfig.app.json
- src/tsconfig.backwards.json
> fix(build): remove the deceleration file from build

- .travis.yml
- dockerfile
- package.json
- scripts/deploy.sh
> feat(ci-cd): add travis

- .travis.yml
- confd/production.tmpl
- package.json
- scripts/check-tmpl.js
> fix(tmpl): add missing config keys

- src/app/app/app-effects/effects/map.app.effects.spec.ts
- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/packages/map-facade/actions/map.actions.ts
> Raise message from pluggin to resolve #654 and #423

- src/app/packages/map-facade/effects/map.effects.ts
> fix bug #827

- src/app/app/app-effects/effects/map.app.effects.spec.ts
- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/app/app-providers/map-source-providers/open-layers-BING-source-provider.ts
- src/app/app/app-providers/map-source-providers/open-layers-IDAHO-source-provider.ts
- src/app/app/app-providers/map-source-providers/open-layers-MapBox-source-provider.ts
- src/app/app/app-providers/map-source-providers/open-layers-OSM-source-provider.ts
- src/app/app/app-providers/map-source-providers/open-layers-TileWMS-source-provider.ts
- src/app/packages/core/less/common.less
- src/app/packages/core/less/z-index-globals.less
- src/app/packages/core/models/case.model.ts
- src/app/packages/core/utils/toast/toast/toast.component.less
- src/app/packages/imagery/imagery-component/imagery.component.spec.ts
- src/app/packages/imagery/imagery-component/manager/imagery.component.manager.ts
- src/app/packages/imagery/model/base-source-provider.model.ts
- src/app/packages/imagery/model/imagery-component-settings.ts
- src/app/packages/map-facade/actions/map.actions.ts
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.html
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.less
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.ts
- src/app/packages/map-facade/reducers/map.reducer.ts
- src/app/packages/map-facade/services/map-facade.service.ts
- src/app/packages/menu/menu/menu.component.less
> feat(overlay): add toast when fails, add progressbar

- src/app/packages/menu/menu/menu.component.spec.ts
- src/app/packages/menu/menu/menu.component.ts
> fix(menu): force element re-render on un-pin

- confd/production.tmpl
- src/app/packages/menu-items/cases/reducers/cases.reducer.ts
- src/assets/config/app.config.json
> fix(default-case): set time dynamically

- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
> fix(layers): layers should be above the overlay

- src/assets/app-loader/app-loader.css
- src/assets/app-loader/app-loader.js
> feat(app-loader): add error handler

- src/app/packages/imagery/model/base-source-provider.model.ts
> fix(overlay): message "Failed to load overlay" only on first fail

- run.sh
- src/app/app/app-effects/effects/map/visualizers.app.effects.ts
- src/app/packages/open-layer-visualizers/annotations.visualizer.ts
- src/app/packages/overlays/models/base-overlay-source-provider.model.ts
Resolve bugs:
#835 
#853 
#832
> fix(annotations) bugs

- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/app/app-providers/overlay-source-providers/multiple-source-provider.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
- src/app/packages/overlays/models/base-overlay-source-provider.model.ts
> fix(multiple-overlays): add support for context analysis

- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.html
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
fix #876 
feat(manual-image-processing) add support for gamma and saturation
fix #860
Bug- screen numbers
> feat(manual-image-processing) add support for gamma and saturation

- confd/production.tmpl
- run.sh
resolve #893 
issue source: https://github.com/AnSyn/ansyn/commit/638b6cbd09d32743a4cab3c36db856986d186f20
> fix(production): add default values to cover config, and fix http-server

- src/app/packages/imagery/model/base-source-provider.model.ts
> fix(toast): message is a value, not a type

- src/app/packages/core/components/imagery-status/imagery-status.component.html
- src/app/packages/core/components/imagery-status/imagery-status.component.less
- src/app/packages/overlays/container/overlays-container.component.html
> design(imagery-status): make icons vertically aligned to middle

- src/app/app/app-effects/effects/filters.app.effects.spec.ts
- src/app/app/app-effects/effects/filters.app.effects.ts
- src/app/packages/menu-items/filters/components/filter-container/filter-container.component.ts
- src/app/packages/menu-items/filters/models/filter.ts
> test(filters-app-effects): add tests to filters app effects

- src/app/app/app-providers/app-providers.module.ts
- src/app/app/app-providers/map-source-providers/open-layers-IDAHO2-source-provider.ts
> feat(idaho2): add idaho2 tiler

- src/app/app/app-effects/effects/tools.app.effects.spec.ts
- src/app/app/app-effects/effects/tools.app.effects.ts
- src/app/packages/core/models/case.model.ts
- src/app/packages/menu-items/cases/components/edit-case/edit-case.component.ts
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
fix(manual-image-processing) saving as case not supported
> fix(manual-image-processing)(872) saving as case not supported

- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.html
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.less
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.ts
- src/app/packages/menu-items/tools/tools/tools.component.html
- src/app/packages/open-layers-map/disabled-map/open-layers-disabled-map.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/overlays/models/base-overlay-source-provider.model.ts
This should fix issues: 
#842 
#873 
#874 
#891
> Perf(manual image processing)(874) when user changing image process parameters exist worker should be stopped

- src/app/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/app/app-providers/overlay-source-providers/multiple-source-provider.ts
> #912 fix entity context

- src/app/app/app-effects/effects/filters.app.effects.spec.ts
- src/app/app/app-effects/effects/filters.app.effects.ts
- src/app/app/app-effects/effects/menu.app.effects.ts
> fix(filters): some filters aren't saved on the case

- src/app/app/app-effects/effects/tools.app.effects.ts
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.html
- src/app/packages/menu-items/tools/components/image-processing-control/image-processing-control.component.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.ts
- src/app/packages/open-layers-map/image-processing/open-layers-image-processing.ts
> fix(manual-image-processing)(872_892) saving as case not supported 

- src/app/packages/menu-items/filters/components/slider-filter-container/slider-filter-container.component.html
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/overlays/container/overlays-container.component.less
> Loading overlays style

- src/app/app/app-effects/effects/map/visualizers.app.effects.ts
- src/app/app/app-effects/effects/status-bar.app.effects.ts
> fix(status-bar)(880) hide pinpoint

- package.json
- src/app/packages/core/services/projection-converter.service.spec.ts
- src/app/packages/core/services/projection-converter.service.ts
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.html
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.spec.ts
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.ts
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.ts
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.ts
> Fix(go to)(692)add go to tool validation

- confd/production.tmpl
- scripts/fix-package-json.js
- src/app/packages/menu-items/cases/services/cases.service.spec.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
- src/assets/config/app.config.json
> Feat(image processing)(890)on link sharing manual image processing parameters should be included

- src/app/packages/open-layers-map/disabled-map/open-layers-disabled-map.ts
> fix(image-processing): disabled map

- src/app/packages/core/less/tooltip.less
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.html
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.less
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.ts
- src/app/packages/menu-items/tools/overlays-display-mode/overlays-display-mode.component.html
- src/app/packages/menu-items/tools/overlays-display-mode/overlays-display-mode.component.less
> fix(tools-menu)(925_927)minor-cosmetics-and-tooltips

- src/app/packages/menu-items/tools/tools/tools.component.ts
> fix(image-processing)(891)when manual image process is active, button should be outlined

- src/app/packages/core/package.json
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/map-facade/components/imagery-container/imagery-container.component.less
- src/app/packages/map-facade/package.json
- src/app/packages/open-layer-center-marker-plugin/package.json
- src/app/packages/open-layer-visualizers/package.json
- src/app/packages/open-layers-map/disabled-map/open-layers-disabled-map.ts
- src/app/packages/open-layers-map/map/open-layers-map.ts
- src/app/packages/open-layers-map/package.json
- src/styles/styles.less
> feat(scale-line): add scale line

- src/app/packages/core/less/tooltip.less
- src/app/packages/map-facade/components/context-menu/context-menu.component.html
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.html
- src/app/packages/menu-items/tools/overlays-display-mode/overlays-display-mode.component.html
- src/app/packages/menu-items/tools/tools/tools.component.html
- src/app/packages/menu/menu/menu.component.html
- src/app/packages/menu/menu/menu.component.less
- src/app/packages/menu/menu/menu.component.ts
add tooltip-value and tooltip-class css support
> task(menu)add pin tooltip and refactor tooltip

- src/app/app/app-effects/effects/cases.app.effects.ts
- src/app/app/app-effects/effects/status-bar.app.effects.ts
- src/app/packages/menu-items/cases/actions/cases.actions.ts
- src/app/packages/menu-items/cases/components/cases-table/cases-table.component.ts
- src/app/packages/menu-items/cases/services/cases.service.ts
> fix(main menu) share case as link with id when sharing via cases menu

- package-lock.json
- package.json
- src/app/app/app-effects/effects/cases.app.effects.spec.ts
- src/app/app/app-effects/effects/cases.app.effects.ts
- src/app/app/app-effects/effects/layers.app.effects.spec.ts
- src/app/app/app-effects/effects/layers.app.effects.ts
- src/app/app/app.module.ts
- src/app/packages/imagery/communicator-service/communicator.service.ts
- src/app/packages/imagery/index.ts
- src/app/packages/menu-items/layers-manager/actions/layers.actions.ts
- src/app/packages/menu-items/layers-manager/reducers/layers.reducer.ts
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.ts
- src/app/packages/open-layer-visualizers/annotations.visualizer.ts
> fix(annotations)(900 832)save to case and fix toggle behavior issues)

- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.less
- src/app/packages/menu-items/tools/go-to/projections/geo/geo.component.less
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.html
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.less
- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.ts
change appearance to include longer ED50 input
> fix(890) round ed50 decimal part to 3 digits 

- src/app/app/app-effects/effects/map/north.app.effects.ts
- src/app/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/packages/open-layers-north-calculations/plugin/north-calculations-plugin.ts
> fix imagery perespective angle

- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/app/app-effects/effects/map/north.app.effects.ts
- src/app/app/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/app/app-providers/overlay-source-providers/idaho-source-provider2.ts
- src/app/packages/open-layers-map/disabled-map/open-layers-disabled-map.ts
- src/app/packages/open-layers-map/openlayers-map/openlayers-map.ts
> Make IDaho 2 as "NotGeoRegistered"

- src/app/packages/open-layer-visualizers/tools/measure-distance.visualizer.ts
> fix edit color to be yellow

- confd/production.tmpl
- src/app/packages/menu-items/cases/services/cases.service.spec.ts
- src/app/packages/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
- src/assets/config/app.config.json
> add image orientation to link

- package.json
- src/app/app/app-effects/effects/core.app.effects.spec.ts
- src/app/app/app-effects/effects/core.app.effects.ts
- src/app/app/app-effects/effects/filters.app.effects.spec.ts
- src/app/app/app-effects/effects/filters.app.effects.ts
- src/app/packages/core/actions/core.actions.ts
- src/app/packages/core/components/imagery-status/imagery-status.component.ts
- src/app/packages/core/models/case.model.ts
- src/app/packages/core/reducers/core.reducer.ts
- src/app/packages/core/services/core.service.ts
- src/app/packages/overlays/actions/overlays.actions.ts
- src/app/packages/overlays/effects/overlays.effects.spec.ts
- src/app/packages/overlays/effects/overlays.effects.ts
- src/app/packages/overlays/reducers/overlays.reducer.ts
- src/app/packages/overlays/services/overlays.service.spec.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
> Task(684)favorites functionality

- src/app/app/app-effects/effects/map/visualizers.annotations.app.effects.spec.ts
- src/app/app/app-effects/effects/map/visualizers.annotations.app.effects.ts
- src/app/packages/menu-items/tools/actions/tools.actions.ts
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.html
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.spec.ts
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.spec.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.ts
- src/app/packages/open-layer-visualizers/annotations.visualizer.ts
>  fix(annotation): fill and stroke colors bugs

- src/app/app/app-effects/effects/filters.app.effects.ts
- src/app/app/app-effects/effects/map/visualizers.app.effects.ts
- src/app/app/app-providers/app-providers.module.ts
- src/app/packages/core/models/case.model.ts
- src/app/packages/menu-items/filters/components/boolean-filter-container/boolean-filter-container.component.html
- src/app/packages/menu-items/filters/components/boolean-filter-container/boolean-filter-container.component.less
- src/app/packages/menu-items/filters/components/boolean-filter-container/boolean-filter-container.component.spec.ts
- src/app/packages/menu-items/filters/components/boolean-filter-container/boolean-filter-container.component.ts
- src/app/packages/menu-items/filters/components/enum-filter-container/enum-filter-container.component.ts
- src/app/packages/menu-items/filters/components/filter-container/filter-container.component.html
- src/app/packages/menu-items/filters/components/filters-collection/filters-collection.component.html
- src/app/packages/menu-items/filters/effects/filters.effects.ts
- src/app/packages/menu-items/filters/filters.module.ts
- src/app/packages/menu-items/filters/models/filter.ts
- src/app/packages/menu-items/filters/models/metadata/boolean-filter-metadata.spec.ts
- src/app/packages/menu-items/filters/models/metadata/boolean-filter-metadata.ts
- src/app/packages/menu-items/filters/models/metadata/enum-filter-metadata.spec.ts
- src/app/packages/menu-items/filters/models/metadata/enum-filter-metadata.ts
- src/app/packages/menu-items/filters/models/metadata/filter-metadata.interface.ts
- src/app/packages/menu-items/filters/models/metadata/slider-filter-metadata.spec.ts
- src/app/packages/menu-items/filters/models/metadata/slider-filter-metadata.ts
- src/app/packages/overlays/services/overlays.service.ts
- src/assets/config/app.config.json
> feat(boolean-filter): add boolean filter metadata

- .travis.yml
- index.ts
- src/app/app/app-effects/effects/map/visualizers.annotations.app.effects.spec.ts
- src/app/app/package-lock.json
- src/app/packages/cesium-map/package-lock.json
- src/app/packages/context/package-lock.json
- src/app/packages/core/models/visualizers/annotations.model.ts
- src/app/packages/core/package-lock.json
- src/app/packages/imagery/package-lock.json
- src/app/packages/login/package-lock.json
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.less
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.spec.ts
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.ts
- src/app/packages/map-facade/package-lock.json
- src/app/packages/menu-items/package-lock.json
- src/app/packages/menu-items/tools/actions/tools.actions.ts
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.ts
- src/app/packages/menu/package-lock.json
- src/app/packages/open-layer-center-marker-plugin/package-lock.json
- src/app/packages/open-layer-visualizers/annotations.visualizer.ts
- src/app/packages/open-layer-visualizers/package-lock.json
- src/app/packages/open-layers-map/package-lock.json
- src/app/packages/overlays/package-lock.json
- src/app/packages/router/package-lock.json
- src/app/packages/status-bar/package-lock.json
- src/assets/package-lock.json
should resolve:
- #1096 
- #1047
> Annotation draw - fix bugs

- src/app/app/app-effects/effects/map.app.effects.ts
- src/app/packages/imagery/communicator-service/communicator.entity.ts
- src/app/packages/map-facade/effects/map.effects.ts
- src/app/packages/map-facade/services/map-facade.service.ts
- src/app/packages/open-layers-map/openlayers-map/openlayers-map.ts
> protect getPosition() method

- src/app/packages/menu/menu/menu.component.ts
should resolve #1098 
dear @asafMasa please take a look!
> fix(menu): pinned menu makes app to crash

- src/app/packages/open-layer-visualizers/overlays/polyline-visualizer.ts
> fix(favorite-overlay-footprint): increase the base stroke width

- src/app/packages/menu-items/tools/go-to/projections/utm/utm.component.ts
should solve issue #980 
decimal formatting - hide decimal part
> go to ED50 round coordinates

- src/app/app/app-providers/app-providers.module.ts
- src/app/app/app-providers/map-source-providers/index.ts
- src/app/app/app-providers/overlay-source-providers/index.ts
- src/assets/config/app.config.json
> resolve 1060: add 4326 map to dev environment

- src/app/app/app-effects/effects/map/visualizers.annotations.app.effects.spec.ts
- src/app/app/app-effects/effects/map/visualizers.annotations.app.effects.ts
- src/app/app/app-effects/effects/tools.app.effects.spec.ts
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.less
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.spec.ts
- src/app/packages/map-facade/components/annotation-context-menu/annotation-context-menu.component.ts
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/menu-items/cases/components/edit-case/edit-case.component.spec.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.spec.ts
- src/app/packages/menu-items/tools/reducers/tools.reducer.ts
- src/app/packages/menu-items/tools/tools/tools.component.ts
- src/app/packages/open-layer-visualizers/annotations.visualizer.ts
- src/app/packages/open-layer-visualizers/entities-visualizer.ts
should resolve:
- #1102 
- #1106
> fix(annotations-bugs): annotation are presented although checked off, stroke fills

- src/app/app/app-effects/effects/filters.app.effects.spec.ts
- src/app/packages/map-facade/effects/map.effects.ts
- src/app/packages/map-facade/reducers/map.reducer.ts
- src/app/packages/status-bar/components/combo-box/combo-box.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.html
- src/app/packages/status-bar/components/status-bar/status-bar.component.less
> fix(status-bar): hide unused buttons

- src/app/app/app-effects/effects/map/visualizers.app.effects.spec.ts
- src/app/app/app-effects/effects/map/visualizers.app.effects.ts
- src/app/app/app-effects/effects/status-bar.app.effects.spec.ts
- src/app/app/app.module.ts
- src/app/packages/core/actions/core.actions.ts
- src/app/packages/core/services/error-handler.service.spec.ts
- src/app/packages/menu-items/tools/components/annotations-control/annotations-control.component.ts
- src/app/packages/menu-items/tools/go-to/go-to/go-to.component.ts
- src/app/packages/menu-items/tools/tools/tools.component.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
- src/app/packages/status-bar/reducers/status-bar.reducer.ts
> Fix(1052) clear exist map interaction when creating new interaction

- src/app/packages/menu-items/tools/tools/tools.component.html
> fix(manual-image-processing)(1181) button should be on when manual image processing is active

- src/app/packages/core/components/imagery-status/imagery-status.component.html
- src/app/packages/core/components/imagery-status/imagery-status.component.ts
- src/app/packages/status-bar/components/status-bar/status-bar.component.ts
> fix(Tool tip- favorites)(1170)  change tooltip behaviour

- confd/production.tmpl
- src/app/app/app-effects/effects/filters.app.effects.ts
- src/app/packages/core/models/case.model.ts
- src/app/packages/map-facade/components/imageries-manager/imageries-manager.component.less
- src/app/packages/map-facade/components/imagery-loader/imagery-loader.component.less
- src/app/packages/menu-items/filters/effects/filters.effects.ts
- src/app/packages/menu-items/filters/models/filter.ts
- src/app/packages/menu-items/filters/models/metadata/boolean-filter-metadata.ts
- src/app/packages/menu-items/filters/models/metadata/enum-filter-metadata.ts
- src/app/packages/menu-items/filters/models/metadata/filter-metadata.interface.ts
- src/app/packages/menu-items/filters/models/metadata/slider-filter-metadata.ts
- src/app/packages/menu-items/filters/services/filters.service.ts
- src/assets/config/app.config.json
- src/configuration/configuration.ts
> fix(filters): Not geo registered should be filtered by default(case)

- src/app/packages/menu-items/filters/components/slider-filter-container/slider-filter-container.component.less
> add Resolution bar new design

- src/app/packages/core/components/imagery-status/imagery-status.component.html
> fix: back to world tooltip

- src/app/@ansyn/imagery/projection-service/projection.service.ts
- src/app/@ansyn/plugins/openlayers/open-layer-visualizers/annotations.visualizer.ts
- src/app/@ansyn/plugins/openlayers/open-layer-visualizers/entities-visualizer.ts
- src/app/@ansyn/plugins/openlayers/open-layer-visualizers/tools/measure-distance.visualizer.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-map/openlayers-map.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/projection/open-layers-projection.service.ts
`projectCollectionAccurately` and `projectCollectionApproximately` to projection service
> feat(projection-service): collection ground to image

- src/app/@ansyn/imagery/model/base-source-provider.model.ts
Hopefully, this solves the bug.
> source-provider: force rendering after all tiles are fetched

- src/app/@ansyn/plugins/openlayers/open-layers-map/disabled-map/disabled-map.component.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-map/openlayers-map.component.spec.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-map/openlayers-map.component.ts
This caused cleanup errors in the tests.
> [Bug] Error during cleanup in the tests

- src/app/@ansyn/imagery/communicator-service/communicator.entity.ts
- src/app/@ansyn/imagery/model/imap.ts
- src/app/@ansyn/map-facade/effects/map.effects.ts
- src/app/@ansyn/plugins/ansyn-plugins.module.ts
- src/app/@ansyn/plugins/openlayers/open-layer-visualizers/visualizers-providers.ts
- src/app/@ansyn/plugins/openlayers/open-layers-image-processing/image-processing-plugin.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/disabled-map/open-layers-disabled-map.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-map/openlayers-map.ts
Created new plugin called image-processing-plugin and moved "setManualImageProcessing" and "setAutoImageProcessing" functionality into it.
should resolve #1300
> Move image processing to plugin

- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
- src/app/@ansyn/ansyn/app-effects/effects/tools.app.effects.ts
- src/app/@ansyn/core/models/case.model.ts
- src/app/@ansyn/imagery/cache-service/cache.service.ts
- src/app/@ansyn/imagery/model/base-source-provider.model.ts
- src/app/@ansyn/menu-items/tools/actions/tools.actions.ts
- src/app/@ansyn/menu-items/tools/components/image-processing-control/image-processing-control.component.ts
- src/app/@ansyn/menu-items/tools/reducers/tools.reducer.ts
Partial fix to #1260 , #1223, full fix for #875
> Fix manual automatic processing states

- src/app/@ansyn/core/components/imagery-status/imagery-status.component.html
- src/app/@ansyn/core/components/imagery-status/imagery-status.component.ts
- src/app/@ansyn/core/utils/time.ts
> fix time tooltip

- src/app/@ansyn/plugins/openlayers/center-marker/center-marker.plugin.ts
- src/app/@ansyn/plugins/openlayers/image-processing/image-processing.plugin.ts
- src/app/@ansyn/plugins/openlayers/north-calculations/north-calculations.plugin.ts
- src/app/@ansyn/plugins/openlayers/visualizers/entities-visualizer.ts
- src/app/@ansyn/plugins/openlayers/visualizers/overlays/frame-visualizer.ts
- src/app/@ansyn/plugins/openlayers/visualizers/overlays/heatmap-visualizer.ts
- src/app/@ansyn/plugins/openlayers/visualizers/overlays/polyline-visualizer.ts
- src/app/@ansyn/plugins/openlayers/visualizers/tools/annotations.visualizer.ts
via https://github.com/AnSyn/ansyn/blob/master/src/app/@ansyn/imagery/model/base-imagery-plugin.ts#L34
> refactor(plugins): init to onInit

- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.spec.ts
- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
- src/app/@ansyn/overlays/actions/overlays.actions.ts
- src/app/@ansyn/overlays/effects/overlays.effects.spec.ts
- src/app/@ansyn/overlays/effects/overlays.effects.ts
- src/app/@ansyn/plugins/openlayers/north-calculations/north-calculations.plugin.ts
> (bug) fix 1338 share case

- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
> fix share link and share case

- src/app/@ansyn/plugins/openlayers/visualizers/region/region.visualizer.ts
#1379 Geo filter - self intersecting polygon causes app to crash
> fixed self-intersection polygon crushes application

- src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.spec.ts
- src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.ts
- src/app/@ansyn/ansyn/app-providers/overlay-source-providers/planet/planet-source-provider.ts
- src/app/@ansyn/context/services/context.service.ts
- src/app/@ansyn/core/models/context.model.ts
- src/app/@ansyn/menu-items/cases/components/edit-case/edit-case.component.ts
- src/app/@ansyn/menu-items/cases/effects/cases.effects.ts
- src/app/@ansyn/menu-items/cases/services/helpers/cases.service.query-params-helper.ts
- src/app/@ansyn/overlays/services/overlays.service.ts
- src/app/@ansyn/status-bar/models/combo-boxes.model.ts
https://github.com/AnSyn/ansyn/issues/1353 related
To launch use: http://localhost:4200/#/?context=areaAnalysis&geopoint=33.81265,-117.91897
> Fix Area Context with Planet

- src/app/@ansyn/ansyn/ansyn/ansyn.component.html
> [Bug] Fix cases routing

- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.html
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.less
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.ts
> Add show "only" to layers

- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.html
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.less
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.ts
> show all layesr button added

- confd/templates/production.tmpl
> removed psscene4band from overlays query

- src/app/@ansyn/ansyn/app-effects/effects/cases.app.effects.spec.ts
- src/app/@ansyn/ansyn/app-effects/effects/cases.app.effects.ts
> cases.app.effects: catch load case errors inside flatMap

- src/app/@ansyn/menu-items/filters/components/boolean-filter-container/boolean-filter-container.component.less
- src/app/@ansyn/menu-items/filters/components/enum-filter-container/enum-filter-container.component.less
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.html
- src/app/@ansyn/menu-items/layers-manager/components/layers-collection/layer-collection.component.less
> remove layers show-all and add marging to only

- karma.conf.js
- src/app/@ansyn/ansyn/app-effects/effects/tools.app.effects.spec.ts
- src/app/@ansyn/ansyn/app-effects/effects/tools.app.effects.ts
- src/app/@ansyn/map-facade/effects/map.effects.ts
> fix backto world where map was not yet loaded

- src/app/@ansyn/menu-items/tools/components/annotations-control/annotations-control.component.html
- src/app/@ansyn/menu-items/tools/components/annotations-control/annotations-control.component.less
- src/app/@ansyn/menu-items/tools/components/annotations-control/annotations-control.component.spec.ts
- src/app/@ansyn/menu-items/tools/components/annotations-control/annotations-control.component.ts
2 Adding an enum for simplicity, readability and preventing Webstorm errors in HTML
> Enhanced styling for fill/stroke

- src/app/@ansyn/ansyn/app-effects/effects/overlays.app.effects.ts
#https://github.com/AnSyn/PrivIssues/issues/24
> fix thumbnail error bug

- src/app/@ansyn/ansyn/app-providers/map-source-providers/open-layers-IDAHO-source-provider.ts
- src/app/@ansyn/ansyn/app-providers/overlay-source-providers/idaho-source-provider.ts
- src/app/@ansyn/core/models/overlay.model.ts
> improved resolution for promise overlays

- src/app/@ansyn/plugins/openlayers/visualizers/region/polygon-search.visualizer.ts
- src/app/@ansyn/status-bar/components/status-bar/status-bar.component.html
> Fix search polygon and share case style's

- src/app/@ansyn/menu-items/layers-manager/components/data-layers-modals/edit-layer/edit-layer.component.html
https://github.com/AnSyn/ansyn/issues/1674
> fix layer validation

- src/app/@ansyn/ansyn/app-effects/effects/core.app.effects.ts
> clear fast loop

- src/app/@ansyn/map-facade/effects/map.effects.ts
> fix out of bounds when pressing back to world view

- src/app/@ansyn/ansyn/app-effects/effects/status-bar.app.effects.ts
- src/app/@ansyn/map-facade/components/imageries-manager/imageries-manager.component.ts
- src/app/@ansyn/map-facade/effects/map.effects.ts
- src/app/@ansyn/plugins/openlayers/visualizers/region/pin-point.visualizer.ts
- src/app/@ansyn/plugins/openlayers/visualizers/region/region.visualizer.ts
> hotfix - geo registered filter bug

- confd/templates/production.tmpl
- src/app/@ansyn/menu/menu.module.ts
- src/app/@ansyn/menu/models/menu-item.model.ts
> add menuItems from config

- src/app/@ansyn/imagery/map/map.component.html
- src/app/@ansyn/imagery/map/map.component.ts
- src/app/@ansyn/imagery/model/base-imagery-map.ts
- src/app/@ansyn/plugins/cesium/cesium-map/cesium-map.ts
- src/app/@ansyn/plugins/openlayers/north-calculations/north-calculations.plugin.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-disabled-map/openlayers-disabled-map.ts
- src/app/@ansyn/plugins/openlayers/open-layers-map/openlayers-map/openlayers-map.ts
> calculate real north on a shadow map

- src/app/@ansyn/plugins/openlayers/plugins/visualizers/algorithms/task-region.visualizer.ts
> polygon-not-updating-when-changing-algorithm-type

- src/app/@ansyn/map-facade/effects/map.effects.ts
- src/app/@ansyn/map-facade/services/map-facade.service.ts
https://github.com/AnSyn/ansyn/issues/2147
> fix position bug

- src/app/@ansyn/ansyn/modules/plugins/cesium/cesium.plugins.module.ts
- src/app/@ansyn/ansyn/modules/plugins/cesium/plugins/mouse-marker/mouse-marker.plugin.ts
- src/app/@ansyn/imagery-cesium/plugins/entities-visualizer/base-entities-visualizer.ts
- src/app/@ansyn/imagery-cesium/public_api.ts
> add mouse marker visualizer for cesium

- src/app/@ansyn/ansyn/ansyn/ansyn.component.less
- src/app/@ansyn/ansyn/modules/overlays/overlay-status/components/back-to-base-map/back-to-base-map.component.less
- src/app/@ansyn/map-facade/components/imagery-status/imagery-status.component.html
this less rule exist already in the component less
> case name move right

- src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.spec.ts
- src/app/@ansyn/ansyn/app-effects/effects/cases/select-case.app.effects.ts
CR this https://github.com/AnSyn/ansyn/pull/2646 first
> set annotation to null on select case

- src/app/@ansyn/map-facade/components/imagery-rotation/imagery-rotation.component.html
- src/app/@ansyn/map-facade/components/imagery-rotation/imagery-rotation.component.less
- src/app/@ansyn/map-facade/components/imagery-rotation/imagery-rotation.component.ts
need to show @carmelorr the result
> enable event propagation in order to close the context menu

- src/app/@ansyn/ansyn/modules/core/components/context-menu/context-menu.component.ts
…ltips from one button will not be hidden by another.
> fix context-menu tooltips z-order

- src/app/@ansyn/ansyn/modules/overlays/overlay-status/overlay-status.component.ts
Registering to changes in selected layers and layers and enabling/disabling the button according to the changes.
> Fixing bug 2803

- src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/visualizers/tools/ansyn.annotations.visualizer.ts
Subscribing the annotations visualizer to the annotation mode on initialization.
> Fixing bug 2805

- src/app/@ansyn/ansyn/modules/status-bar/components/filters-panel/filters-panel.component.html
> adding tooltip to show favorites filter

- src/app/@ansyn/ansyn/modules/overlays/overlay-status/overlay-status.component.html
- src/app/@ansyn/ansyn/modules/overlays/overlay-status/overlay-status.component.less
> 3094-more-buttons-not-aligned-3102-background-on-hover

- src/app/@ansyn/ansyn/modules/core/forms/combo-box-trigger/combo-box-trigger.component.less
> 3136-data-input-filter-button-overflow-chrome-44

- package-lock.json
- package.json
- src/app/@ansyn/ansyn/package.json
Color changes in time picker
https://github.com/AnSyn/date-time-picker/pull/5/files
> Upgrade time-picker package (some new colors)

- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
- src/app/@ansyn/ansyn/modules/overlays/overlay-status/effects/overlay-status.effects.ts
- src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/anaglyph-sensor/service/anaglyph-sensor.service.ts
- src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/image-processing/image-processing.plugin.ts
- src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/north-calculations/north-calculations.plugin.ts
- src/app/@ansyn/imagery-cesium/mapSourceProviders/cesium-BING-source-provider.ts
- src/app/@ansyn/imagery-cesium/mapSourceProviders/cesium-GEO-SERVER-source-provider.ts
- src/app/@ansyn/imagery-cesium/mapSourceProviders/cesium-OSM-source-provider.ts
- src/app/@ansyn/imagery-cesium/mapSourceProviders/cesium-PLANET-source-provider.ts
- src/app/@ansyn/imagery-cesium/mapSourceProviders/cesium-open-aerial-source-provider.ts
- src/app/@ansyn/imagery-cesium/maps/cesium-map/cesium-map.ts
- src/app/@ansyn/imagery-video/providers/imagery-video-provider.ts
- src/app/@ansyn/imagery/communicator-service/communicator.entity.ts
- src/app/@ansyn/imagery/model/base-imagery-map.ts
- src/app/@ansyn/imagery/model/base-map-source-provider.ts
- src/app/@ansyn/imagery/model/imagery-layer.model.ts
- src/app/@ansyn/imagery/public_api.ts
- src/app/@ansyn/ol/mapSourceProviders/open-layers.map-source-provider.ts
- src/app/@ansyn/ol/maps/open-layers-map/openlayers-map/openlayers-map.ts
- src/app/@ansyn/ol/maps/openlayers-disabled-map/openlayers-disabled-map.ts
- src/app/@ansyn/ol/plugins/entities-visualizer.ts
> 3239 add types for map layers

- src/app/@ansyn/ansyn/modules/overlays/overlay-status/components/back-to-base-map/back-to-base-map.component.less
> fix-base-map-btn-in-small-windows

- src/app/@ansyn/ansyn/modules/menu-items/help/components/help.component.less
> int-634-help-buttons-dont-look-good

- src/app/@ansyn/ansyn/modules/overlays/overlay-status/effects/overlay-status.effects.ts
- src/app/@ansyn/imagery/public_api.ts
> deleted scanned area on second click

- src/app/@ansyn/map-facade/components/imagery-status/imagery-status.component.html
> disabled prespective button on noGeoRegistration

- src/app/@ansyn/ansyn/modules/plugins/openlayers/plugins/visualizers/tools/measure-distance.visualizer.ts
> int-733-end-measure-after-hide-layers

- src/app/@ansyn/ansyn/modules/status-bar/components/tree-view/tree-view.component.html
- src/app/@ansyn/ansyn/modules/status-bar/components/tree-view/tree-view.component.less
- src/app/@ansyn/ansyn/modules/status-bar/components/tree-view/tree-view.component.spec.ts
- src/app/@ansyn/ansyn/modules/status-bar/components/tree-view/tree-view.component.ts
> add show all and only buttons

- src/app/@ansyn/ansyn/app-effects/effects/cases.app.effects.ts
- src/app/@ansyn/ansyn/app-effects/effects/map.app.effects.ts
- src/app/app/router/services/router.service.ts
- src/app/app/sentinel/open-layers-sentinel-source-provider.ts
> fixing a bug that caused not showing the overlay when pasting a link on link

- angular.json
- ngcc.config.js
…ng babel to the commonJsDependencies
> fix launch warnings angular10

- src/app/@ansyn/ansyn/modules/core/components/angle-filter/angle-filter.component.spec.ts
- src/app/@ansyn/ansyn/modules/core/components/angle-filter/angle-filter.component.ts
> change overlays orientation in angle window

- src/app/@ansyn/imagery-video/components/imagery-video/imagery-video.component.ts
fixes a crash when trying to display a video overlay
>  video overlay fix

- src/app/@ansyn/ansyn/modules/menu-items/results/components/results-table/results-table.component.ts
- src/app/@ansyn/ansyn/modules/overlays/components/timeline/timeline.component.ts
> Revert "when open overlay split to 2 screen"

- package-lock.json
- src/app/@ansyn/ansyn/services/overlay-out-of-bounds/overlay-out-of-bounds.service.ts
> back to extent on not georegistered overlay

- src/app/@ansyn/ansyn/modules/menu-items/cases/reducers/cases.compare.ts
> fix crash in back to base map

- src/app/@ansyn/ansyn/modules/status-bar/components/advanced-search/advanced-search.component.html
- src/app/@ansyn/ansyn/modules/status-bar/components/advanced-search/advanced-search.component.less
- src/app/@ansyn/ansyn/modules/status-bar/components/tools/export-maps-popup/export-maps-popup.component.less
* Remove space evenly in export modal
* Replace grid css settings with flex
> Change css for support chrome old versions

- src/app/@ansyn/ansyn/modules/entities-table/components/entities-table/entities-table.component.html
- src/app/@ansyn/ansyn/modules/entities-table/components/entities-table/entities-table.component.less
- src/app/@ansyn/ansyn/modules/menu-items/layers-manager/components/layer-menu/layer-menu.component.html
- src/app/@ansyn/ansyn/modules/menu-items/layers-manager/components/layer-menu/layer-menu.component.less
- src/app/@ansyn/ansyn/modules/menu-items/layers-manager/components/layers-manager/layers-manager.component.less
- src/app/@ansyn/ansyn/modules/plugins/components/imagery-change-map/imagery-change-map.component.less
* Fix position of map changer
* Fix bug of layers list overflowing
> * Fix styling bugs
